<!-- .github/workflows/upstream-sync.yml -->
name: Upstream Sync

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3

    - name: Pull from upstream
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote add upstream https://github.com/davidshimjs/qrcodejs.git || true
        git fetch upstream
        git merge upstream/master --allow-unrelated-histories -m "Sync with upstream"
        git push
